name: Build and Push Image

on:
  push:
    paths:
      - 'Dockerfile'
      - '.gitea/workflows/build-image.yaml'
    #branches:
     # - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        run: |
          git clone http://192.168.122.10:3000/jaj/infrastructure-lab.git repo
          cd repo
          git checkout $GITHUB_SHA

      - name: Login to Gitea Registry
        run: |
          echo "${{ secrets.REGISTRY_TOKEN }}" | \
            docker login 192.168.122.10:3000 \
            --username "${{ secrets.REGISTRY_USER }}" \
            --password-stdin

      - name: Build image
        run: |
          cd repo
          docker build \
            -t 192.168.122.10:3000/jaj/infrastructure-lab:${{ gitea.sha }} \
            -t 192.168.122.10:3000/jaj/infrastructure-lab:latest \
            .

      - name: Push image
        run: |
          docker push 192.168.122.10:3000/jaj/infrastructure-lab:${{ gitea.sha }}
          docker push 192.168.122.10:3000/jaj/infrastructure-lab:latest
